# config.yml
mongo:
  host: localhost
  port: 27017
  database: bnemu
  username: root
  password: rootpass

realm:
  name: "bnemu"
  description: "bnemu Realm"

bnftp:
  filesDir: "files"

server:
  bncs:
    port: 6112
  d2cs:
    port: 6113
    host: "172.16.1.38"
  d2gs:
    port: 4000
    host: "172.16.1.38"
  telnet:
    port: 23
